### ISSUE TITLE
watchGoImporter error in log

### ISSUE THREAD

**Issue by olizilla** [forestpm/forest#12]
```
(node:6222) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at watchGoImporter (/Users/oli/Code/forestpm/forest/lib/forest.js:518:26)
    at /Users/oli/Code/forestpm/forest/lib/forest.js:573:11
(node:6222) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
```

**Comment by andrew** [comment]
I have seen this error before, but haven't been able to replicate it enough to fix (not exactly sure what the bad data is)

I think we just validate the data at the same of `watchGoImporter` and throw it away if it's not right (or yolo and wrap the whole thing in a try-catch)

**Comment by andrew** [comment]
I think I've fixed this but reopen if it's still happening after you've updated
